-- Run once in a NEW Supabase database/schema. Abort if operational schema exists.
-- All legacy timestamp-without-zone values are UTC.
begin;
create schema trustflow;
revoke all on schema trustflow from public, anon, authenticated;

create table trustflow."Empresas" (
 "EmpresaId" integer generated by default as identity primary key,
 "Tipo" text not null, "Nome" text not null, "Ativo" smallint not null default 1,
 unique ("Tipo", "Nome")
);
create table trustflow."Produtos" (
 "ProdutoId" integer generated by default as identity primary key,
 "Nome" text not null unique, "TipoProduto" text not null default 'Refrigerado',
 "TemperaturaMin" double precision, "TemperaturaMax" double precision not null,
 "CustoUnitario" numeric(18, 2) not null default 0, "Ativo" smallint not null default 1
);
create table trustflow."CentrosDistribuicao" (
 "CentroId" integer generated by default as identity primary key,
 "Codigo" text not null unique, "Nome" text not null, "Cidade" text, "UF" text,
 "Ativo" smallint not null default 1
);
create table trustflow."Dispositivos" (
 "SensorId" text primary key, "NomeExibicao" text, "Tipo" text,
 "Ativo" smallint not null default 1, "Status" text not null default 'Disponível',
 "Bateria" double precision, "BateriaVolts" numeric(4,3), "SinalRssi" smallint, "Calibracao" text, "Ciclos" integer not null default 0,
 "UltimaComunicacao" timestamp without time zone
);
create table trustflow."Fretes" (
 "FreteId" integer generated by default as identity primary key,
 "NumeroNF" text not null,
 "FornecedorId" integer not null references trustflow."Empresas"("EmpresaId"),
 "ClienteId" integer not null references trustflow."Empresas"("EmpresaId"),
 "TransportadoraId" integer not null references trustflow."Empresas"("EmpresaId"),
 "CentroDistribuicaoId" integer references trustflow."CentrosDistribuicao"("CentroId"),
 "ProdutoId" integer not null references trustflow."Produtos"("ProdutoId"),
 "SensorId" text not null references trustflow."Dispositivos"("SensorId"),
 "Volume" integer not null check ("Volume" > 0),
 "ValorCarga" numeric(18,2) not null default 0,
 "ValorUnitarioCarga" numeric(18, 4) not null default 0,
 "TemperaturaLimite" double precision, "TemperaturaMinima" double precision,
 "TemperaturaMaxima" double precision, "DestinoTexto" text,
 "Status" text not null default 'ATIVO', "StatusPreditivo" text not null default 'OK',
 "StatusOperacional" text not null default 'ESTABILIZANDO',
 "Violado" smallint not null default 0, "TempoEstabilizacaoMinutos" integer not null default 5,
 "InicioEm" timestamp without time zone not null default (now() at time zone 'UTC'),
 "FimEm" timestamp without time zone, "HashContrato" text
);
create unique index if not exists trustflow_one_active_freight_per_device
 on trustflow."Fretes"("SensorId") where "Status" = 'ATIVO';
create table trustflow."Telemetria" (
 "Id" bigint generated by default as identity primary key,
 "FreteId" integer references trustflow."Fretes"("FreteId"),
 "SensorId" text not null references trustflow."Dispositivos"("SensorId"),
 "Evento" text, "Temperatura" double precision, "Umidade" double precision,
 "StatusRede" text, "DataDispositivo" timestamp without time zone,
 "DataRecebimento" timestamp without time zone not null default (now() at time zone 'UTC')
);
create index if not exists trustflow_telemetria_frete_data
 on trustflow."Telemetria"("FreteId", "DataRecebimento");
create table trustflow."Alertas" (
 "AlertaId" bigint generated by default as identity primary key,
 "FreteId" integer references trustflow."Fretes"("FreteId"),
 "TelemetriaId" bigint references trustflow."Telemetria"("Id"),
 "SensorId" text, "Nivel" text, "Tipo" text,
 "Mensagem" text, "ValorMedido" double precision, "Limite" double precision,
 "CriadoEm" timestamp without time zone not null default (now() at time zone 'UTC'),
 "ReconhecidoEm" timestamp without time zone, "ReconhecidoPor" text, "Observacao" text,
 "ResolvidoEm" timestamp without time zone
);
create table trustflow."EventosFrete" (
 "EventoId" bigint generated by default as identity primary key,
 "FreteId" integer not null references trustflow."Fretes"("FreteId"),
 "TipoEvento" text not null, "Descricao" text,
 "CriadoEm" timestamp without time zone not null default (now() at time zone 'UTC')
);
-- NENHUM GRANT de acesso à Data API: operações só pelo backend controlado.
-- RLS adicional: a sessão regular não terá políticas de acesso direto.
alter table trustflow."Empresas" enable row level security;
alter table trustflow."Produtos" enable row level security;
alter table trustflow."CentrosDistribuicao" enable row level security;
alter table trustflow."Dispositivos" enable row level security;
alter table trustflow."Fretes" enable row level security;
alter table trustflow."Telemetria" enable row level security;
alter table trustflow."Alertas" enable row level security;
alter table trustflow."EventosFrete" enable row level security;

create table trustflow."RefrigeradosFixos" (
 "RefrigeradoId" integer generated by default as identity primary key,
 "Nome" text not null, "Local" text not null, "Tipo" text not null,
 "SensorId" text not null references trustflow."Dispositivos"("SensorId"),
 "TemperaturaMin" double precision not null, "TemperaturaMax" double precision not null,
 "CriadoEm" timestamp without time zone not null default (now() at time zone 'UTC'),
 "DesvinculadoEm" timestamp without time zone, "PosicaoPlanta" text,
 check ("TemperaturaMin" < "TemperaturaMax")
);
create unique index one_active_fixed_device on trustflow."RefrigeradosFixos"("SensorId") where "DesvinculadoEm" is null;
create unique index one_active_floor_position on trustflow."RefrigeradosFixos"("PosicaoPlanta") where "DesvinculadoEm" is null;
create table trustflow."LeiturasFixas" (
 "Id" bigint generated by default as identity primary key,
 "RefrigeradoId" integer not null references trustflow."RefrigeradosFixos"("RefrigeradoId"),
 "SensorId" text not null references trustflow."Dispositivos"("SensorId"),
 "LeituraId" text not null, "Temperatura" double precision not null,
 "MedidoEm" timestamp without time zone not null,
 "DataRecebimento" timestamp without time zone not null default (now() at time zone 'UTC'),
 "WifiRSSI" integer,
 unique("SensorId", "LeituraId")
);
create index fixed_history on trustflow."LeiturasFixas"("RefrigeradoId", "SensorId", "MedidoEm", "Id");
create index pending_alarms on trustflow."Alertas"("FreteId", "CriadoEm" desc, "AlertaId" desc) where "ResolvidoEm" is null;
create table trustflow.profiles (
 id uuid primary key references auth.users(id),
 nome text not null,
 perfil text not null check (perfil in ('ADMIN', 'OPERADOR', 'SUPPLY')),
 ativo boolean not null default true,
 criado_em timestamptz not null default now()
);
alter table trustflow."RefrigeradosFixos" enable row level security;
alter table trustflow."LeiturasFixas" enable row level security;
alter table trustflow.profiles enable row level security;
revoke all on all tables in schema trustflow from public, anon, authenticated;
revoke all on all sequences in schema trustflow from public, anon, authenticated;
-- No Data API grants. All operations require server-side Auth and role checks.
-- Vercel initially connects with the database owner via a secret DATABASE_URL.
commit;
